### ISSUE TITLE
login success but push fail with err_msg "denied: requested access to the resource is denied"

### ISSUE THREAD

**Issue by iamtmoe** [denverdino/acr-login#12]
i follow the readme example, set USER_NAME and PASSWORD，github action login success but push fails
below is github action config file:
```yml
- name: Check out the repo
   uses: actions/checkout@v2

- name: Login to ACR
  uses: aliyun/acr-login@v1
  with:
    login-server: https://registry.cn-beijing.aliyuncs.com
    region-id: cn-beijing
    username: "${{ secrets.USERNAME }}"
    password: "${{ secrets.PASSWORD }}"

- name: Build and push image
  env:
    IMAGE_TAG: latest
  run: |
    docker build -t registry.cn-beijing.aliyuncs.com/tmoe/resume_web:$IMAGE_TAG .
    docker push registry.cn-beijing.aliyuncs.com/tmoe/resume_web:$IMAGE_TAG
```
below is action fail screenshot:
![image](https://user-images.githubusercontent.com/41809433/138659612-d36fe5f1-3461-412a-a622-f2a8758b36e4.png)

I try to exec `docker push registry.cn-beijing.aliyuncs.com/tmoe/resume_web:$IMAGE_TAG` on my local machine, and it works, but github action can not work. before use acr, i push to dockerhub, it works too.
